name: petshop_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# --- BAGIAN INI YANG DIPERBAIKI ---
# Semua konfigurasi flutter (assets & fonts) harus ada di bawah SATU 'flutter:'
flutter:
  uses-material-design: true

  # 1. Assets Gambar
  assets:
    - assets/images/

  # 2. Custom Fonts (Dimasukkan di sini)
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700